<#
Version: 1.0
Author: 
- Tom Coleman @albanytech
Script: RemediateWhoAmiICanaryToken
Description: Adds a canary Token to Registry https://blog.thinkst.com/2022/09/sensitive-command-token-so-much-offense.html Go To https://www.canarytokens.org to generate your token.  This will trigger alerts in defender which you will have to tune out.
Release notes:
Version 1.0: Init
Run as: Admin/User
Context: 64 Bit
#> 

## Sensitive command token generated by Thinkst Canary

$Path1 = 'Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\wmic.exe', 'Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\wmic.exe'
$Path2 = 'Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\SilentProcessExit\wmic.exe', 'Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows NT\CurrentVersion\SilentProcessExit\wmic.exe'

$Name1 = 'GlobalFlag'
$Name2 = 'ReportingMode'
$Name3 = 'MonitorProcess'

$Value1 = '00000512'
$Value2 = '00000001'
##Ensure you change ****INSERTYOURUNIQUECANARYTOKENHERE**** to the token you generate at https://www.canarytokens.org
$Value3 = 'cmd.exe /c start /min powershell.exe -windowstyle hidden -command "$($u=$(\"u$env:username\" -replace(''[^\x00-\x7f]|\s'', ''''))[0..63] -join '''';$c=$(\"c$env:computername\" -replace(''[^\x00-\x7f]|\s'', ''''));Resolve-DnsName -Name \"$c.UN.$u.CMD.****INSERTYOURUNIQUECANARYTOKENHERE****.canarytokens.com\")"'

$type = 'DWORD'


Foreach ($i In $Path1)
{
If (!(Test-Path $i)) {

    New-Item -Path $i -Force | Out-Null
## command that will be watched for
    New-ItemProperty -Path $i -Name $Name1 -Value $Value1 -PropertyType $Type -Force -ea SilentlyContinue;
  }  
}

## magic unique canarytoken that will be fired when this command is executed

Foreach ($i In $Path2)
{
If (!(Test-Path $i)) {
    New-Item -Path $i -Force | Out-Null
    New-ItemProperty -Path $i -Name $Name2 -Value $Value2 -PropertyType $Type -Force -ea SilentlyContinue;

    New-ItemProperty -Path $i -Name $Name3 -Value $Value3 -Force -ea SilentlyContinue;
  }  


}